name: AutomaticBroadcast
version: 1.2.5
author: Pandaaa
main: ca.pandaaa.automaticbroadcast.AutomaticBroadcast
softdepend: [PlaceHolderAPI]
api-version: 1.16
commands:
  automaticbroadcast:
    aliases: [ab, autobroadcast]
    description: Automatic Broadcast commands.

permissions:
  automaticbroadcast.exempt:
    default: op
  automaticbroadcast.config:
    default: op
